dist: Bionic
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
env:
  - product_filename="*ugglite*.zip" chat_id="-1001378095587"
install: |
  sudo apt-get install python3-setuptools python3-pip python3 python
  wget https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh
  sudo chmod +x android_build_env.sh
  sudo ./android_build_env.sh
  pip3 install wheel
  git clone https://github.com/RomashkaGang/PublishBot ~/PublishBot
  pip3 install --user -r /home/travis/PublishBot/requirements.txt
  repo init -u https://github.com/SKYHAWK-Recovery-Project/platform_manifest_twrp_omni.git -b 9.0 --depth=1
  time repo sync -c -f -q --force-sync --no-clone-bundle --no-tags -j8
  git clone https://github.com/frelein29/twrp_device_xiaomi_ugglite device/xiaomi/ugglite -b shrp
  wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/android-9.0.0_r1/clang-4691093.tar.gz
  mkdir clang-4691093
  tar xvf clang-4691093.tar.gz --directory clang-4691093
  mkdir -p prebuilts/clang/host/linux-x86/
  cp clang-4691093 prebuilts/clang/host/linux-x86/
  mv clang-4691093 prebuilts/clang/host/linux-x86/clang-4691093
before_script: |
  python3 /home/travis/PublishBot/main.py --before
script: |
  ls -al /proc/self/cwd
  ls prebuilts/clang/host/linux-x86/
  ls prebuilts/clang/host/linux-x86/clang-4691093/bin/
  . build/envsetup.sh
  lunch omni_ugglite-eng
  export ALLOW_MISSING_DEPENDENCIES=true
  mka recoveryimage -j12
  output_file=$(find ./out/target/product/ugglite/ -name "*ugglite*.zip")
  if [ -f $output_file ]; then
    cp $output_file ./
  else
    python3 /home/travis/PublishBot/main.py --after
    exit 1
  fi
after_success: |
  python3 /home/travis/PublishBot/main.py --after
after_failure: |
  python3 /home/travis/PublishBot/main.py --after
