dist: Bionic
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
env:
  - product_filename="*ugglite*.zip" chat_id="-1001378095587"
install: |
  git clone https://github.com/RomashkaGang/PublishBot ~/PublishBot && pip3 install --user -r /home/travis/PublishBot/requirements.txt && git clone https://github.com/frelein29/twrp_device_xiaomi_ugglite device/xiaomi/ugglite -b shrp
before_script: |
  python3 /home/travis/PublishBot/main.py --before
script: |
  ls -al /proc/self/cwd
after_success: |
  python3 /home/travis/PublishBot/main.py --after
after_failure: |
  python3 /home/travis/PublishBot/main.py --after
